message(STATUS "${BoldBlue}───────────────────────────────────────────────${ColourReset}")
message(STATUS "${Blue}[CMAKE_BUILD_TYPE       ]${ColourReset}: ${CMAKE_BUILD_TYPE}")
message(STATUS "${Blue}[GIT_HASH               ]${ColourReset}: ${GIT_HASH}")
message(STATUS "${Blue}[CMAKE_CXX_FLAGS        ]${ColourReset}: ${CMAKE_CXX_FLAGS}")
if(${CMAKE_BUILD_TYPE} STREQUAL "Release")
    message(STATUS "${Blue}[CMAKE_CXX_FLAGS_RELEASE]${ColourReset}: ${CMAKE_CXX_FLAGS_RELEASE}")
else()
    message(STATUS "${Blue}[CMAKE_CXX_FLAGS_DEBUG  ]${ColourReset}: ${CMAKE_CXX_FLAGS_DEBUG}")
endif()
message(STATUS "${BoldBlue}───────────────────────────────────────────────${ColourReset}")